### ISSUE TITLE
ease of access

### ISSUE THREAD

**Issue by Drago-Cuven** [Sammyueru/Scratchworks#1]
srsly? why couldn't you have made it an actual extension everyone could use more easily? i'm on a chromebook. that makes this impossible to use!

**Comment by Sammyueru** [comment]
Shut up if you don't like it make your own and see how it's not possible.
The only other way is to program a new TurboWarp mod.
Also a chromebook? Really?

**Comment by Sammyueru** [comment]
-

**Comment by Drago-Cuven** [comment]
dude I'm not trying to be rude. I'm just saying you could do something like
that with an UNSANDBOXED extension.

**Comment by Sammyueru** [comment]
You can't do it an unsandboxed extension.
Sorry for me being rude.
However Chromebook support can't be added unless you mess with the TurboWarp source code which I have tried and didn't work out for me.
